import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
import { connect } from "@tursodatabase/serverless";
import { calculateComplexity } from "@/lib/complexity";

export type TranslationStatus = "missing" | "partly_missing" | "draft" | "translated" | "reviewed";
export type ReviewStatus = "unreviewed" | "needs_review" | "approved" | "rejected";
export type Phrase = { id:number; icelandic:string; meaning:string; literal:string; why:string; audioUrl:string; source:string; category:string; mastery:number; reviews:number; complexity:number; level:number; correctStreak:number; nextReviewAt:string; translationStatus:TranslationStatus; reviewStatus:ReviewStatus; adminNotes:string; translatedBy:string; updatedAt:string; archivedAt:string };
export type AdminFilters = { query?:string; source?:string; translationStatus?:string; reviewStatus?:string; level?:number; sort?:"icelandic"|"level"|"complexity"|"source"|"updated"; direction?:"asc"|"desc"; page?:number; archived?:boolean };
export type DashboardData = { phrases:Phrase[]; stats:{total:number; mastered:number; reviews:number}; study:{currentLevel:number; totalLevels:number; levelMastered:number} };
type StatusCount = { status:string; count:number };
export type AdminStatistics = { total:number; translated:number; approved:number; ready:number; translationStatuses:StatusCount[]; reviewStatuses:StatusCount[]; completeness:{meaning:number;literal:number;why:number;complete:number}; sources:Array<{source:string;total:number;translated:number;reviewed:number;approved:number;missing:number}>; levels:Array<{level:number;total:number;translated:number;approved:number}> };
export type ExpressionInput = Pick<Phrase,"icelandic"|"meaning"|"literal"|"why"|"audioUrl"|"source"|"category"|"translationStatus"|"reviewStatus"|"adminNotes">;

const remote = process.env.TURSO_DATABASE_URL && process.env.TURSO_AUTH_TOKEN ? connect({ url:process.env.TURSO_DATABASE_URL, authToken:process.env.TURSO_AUTH_TOKEN }) : null;
const dataDir = path.join(process.cwd(), "data");
const localPath = process.env.SQLITE_PATH ? path.resolve(process.env.SQLITE_PATH) : path.join(dataDir, "phrases.db");
if (!remote) { fs.mkdirSync(path.dirname(localPath), { recursive:true }); }
const local = remote ? null : new Database(localPath);
if (local) { local.pragma("busy_timeout = 10000"); local.pragma("journal_mode = WAL"); }

const schema = [
  `CREATE TABLE IF NOT EXISTS phrases (id INTEGER PRIMARY KEY AUTOINCREMENT, icelandic TEXT NOT NULL, english TEXT NOT NULL DEFAULT '', pronunciation TEXT NOT NULL DEFAULT '', meaning TEXT NOT NULL DEFAULT '', literal TEXT NOT NULL DEFAULT '', why TEXT NOT NULL DEFAULT '', audio_url TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT 'Tilvitnun', category TEXT NOT NULL DEFAULT 'Everyday', mastery INTEGER NOT NULL DEFAULT 0, reviews INTEGER NOT NULL DEFAULT 0, complexity INTEGER NOT NULL DEFAULT 0, level INTEGER NOT NULL DEFAULT 0, correct_streak INTEGER NOT NULL DEFAULT 0, next_review_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, translation_status TEXT NOT NULL DEFAULT 'missing', review_status TEXT NOT NULL DEFAULT 'unreviewed', admin_notes TEXT NOT NULL DEFAULT '', translated_by TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, archived_at TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS study_state (id INTEGER PRIMARY KEY CHECK (id=1), current_level INTEGER NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS user_study_state (user_id TEXT PRIMARY KEY, current_level INTEGER NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS user_phrase_progress (user_id TEXT NOT NULL, phrase_id INTEGER NOT NULL, mastery INTEGER NOT NULL DEFAULT 0, reviews INTEGER NOT NULL DEFAULT 0, correct_streak INTEGER NOT NULL DEFAULT 0, next_review_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id, phrase_id))`,
];

async function init() {
  if (remote) { await remote.batch(schema, "immediate"); return; }
  local!.exec(schema.join(";"));
}
const ready = init();
async function all<T=Record<string,unknown>>(sql:string, params:(string|number|null)[]=[]):Promise<T[]> { await ready; if (remote) { const s=await remote.prepare(sql); return (await s.all(params)) as T[]; } return local!.prepare(sql).all(...params) as T[]; }
async function get<T=Record<string,unknown>>(sql:string, params:(string|number|null)[]=[]):Promise<T|undefined> { const rows=await all<T>(sql,params); return rows[0]; }
async function run(sql:string, params:(string|number|null)[]=[]):Promise<{lastInsertRowid?:number}> { await ready; if (remote) { const s=await remote.prepare(sql); const r=await s.run(params); return { lastInsertRowid:Number(r.lastInsertRowid ?? 0) }; } const r=local!.prepare(sql).run(...params); return {lastInsertRowid:Number(r.lastInsertRowid)}; }

const adminSelect = `SELECT id,icelandic,meaning,literal,why,audio_url AS audioUrl,source,category,mastery,reviews,complexity,level,correct_streak AS correctStreak,next_review_at AS nextReviewAt,translation_status AS translationStatus,review_status AS reviewStatus,admin_notes AS adminNotes,translated_by AS translatedBy,updated_at AS updatedAt,archived_at AS archivedAt FROM phrases`;

export async function getDashboardData(userId:string):Promise<DashboardData> {
  await run("INSERT OR IGNORE INTO user_study_state (user_id,current_level) VALUES (?,1)",[userId]);
  const state=await get<{currentLevel:number}>("SELECT current_level AS currentLevel FROM user_study_state WHERE user_id=?",[userId]);
  const currentLevel=state?.currentLevel ?? 1;
  const max=await get<{totalLevels:number}>("SELECT COALESCE(MAX(level),1) AS totalLevels FROM phrases WHERE archived_at=''" );
  const phrases=await all<Phrase>(`SELECT p.id,p.icelandic,p.meaning,p.literal,p.why,p.audio_url AS audioUrl,p.source,p.category,COALESCE(x.mastery,0) mastery,COALESCE(x.reviews,0) reviews,p.complexity,p.level,COALESCE(x.correct_streak,0) correctStreak,COALESCE(x.next_review_at,CURRENT_TIMESTAMP) nextReviewAt,p.translation_status translationStatus,p.review_status reviewStatus,p.admin_notes adminNotes,p.translated_by translatedBy,p.updated_at updatedAt,p.archived_at archivedAt FROM phrases p LEFT JOIN user_phrase_progress x ON x.phrase_id=p.id AND x.user_id=? WHERE p.level=? AND p.archived_at='' ORDER BY p.complexity,p.id`,[userId,currentLevel]);
  const totals=await get<{total:number;mastered:number;reviews:number}>("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN x.mastery>=4 THEN 1 ELSE 0 END),0) mastered,COALESCE(SUM(x.reviews),0) reviews FROM phrases p LEFT JOIN user_phrase_progress x ON x.phrase_id=p.id AND x.user_id=? WHERE p.archived_at=''",[userId]);
  return {phrases,stats:{total:totals?.total??0,mastered:totals?.mastered??0,reviews:totals?.reviews??0},study:{currentLevel,totalLevels:max?.totalLevels??1,levelMastered:phrases.filter(p=>p.mastery>=2).length}};
}
export async function createPhrase(input:Pick<Phrase,"icelandic"|"meaning"|"literal"|"why"|"source"|"category">) { const c=calculateComplexity(input.icelandic); const x=await get<{preceding:number}>("SELECT COUNT(*) preceding FROM phrases WHERE complexity<=?",[c]); await run("INSERT INTO phrases(icelandic,english,meaning,literal,why,source,category,complexity,level) VALUES(?,?,?,?,?,?,?,?,?)",[input.icelandic,input.meaning,input.meaning,input.literal,input.why,input.source,input.category,c,Math.floor((x?.preceding??0)/20)+1]); }
export async function reviewPhrase(userId:string,id:number,remembered:boolean) { await run("INSERT OR IGNORE INTO user_study_state(user_id,current_level) VALUES(?,1)",[userId]); await run("INSERT OR IGNORE INTO user_phrase_progress(user_id,phrase_id) VALUES(?,?)",[userId,id]); const p=await get<{correctStreak:number;level:number}>("SELECT x.correct_streak correctStreak,p.level FROM phrases p JOIN user_phrase_progress x ON x.phrase_id=p.id AND x.user_id=? WHERE p.id=?",[userId,id]); if(!p)return; const streak=remembered?p.correctStreak+1:0; const intervals=[2,10,1440,4320,10080,20160,43200]; const next=new Date(Date.now()+(remembered?intervals[Math.min(streak,6)]:2)*60000).toISOString(); await run("UPDATE user_phrase_progress SET mastery=MAX(0,MIN(5,mastery+?)),reviews=reviews+1,correct_streak=?,next_review_at=? WHERE user_id=? AND phrase_id=?",[remembered?1:-1,streak,next,userId,id]); const incomplete=await get<{incomplete:number}>("SELECT COUNT(*) incomplete FROM phrases p LEFT JOIN user_phrase_progress x ON x.phrase_id=p.id AND x.user_id=? WHERE p.level=? AND COALESCE(x.mastery,0)<2 AND p.archived_at=''",[userId,p.level]); const max=await get<{totalLevels:number}>("SELECT COALESCE(MAX(level),1) totalLevels FROM phrases WHERE archived_at='' "); if((incomplete?.incomplete??1)===0&&p.level<(max?.totalLevels??1)) await run("UPDATE user_study_state SET current_level=? WHERE user_id=? AND current_level=?",[p.level+1,userId,p.level]); }
export async function setStudyLevel(userId:string,requested:number) { const max=await get<{totalLevels:number}>("SELECT COALESCE(MAX(level),1) totalLevels FROM phrases WHERE archived_at='' "); await run("INSERT OR IGNORE INTO user_study_state(user_id,current_level) VALUES(?,1)",[userId]); await run("UPDATE user_study_state SET current_level=? WHERE user_id=?",[Math.max(1,Math.min(max?.totalLevels??1,Math.trunc(requested))),userId]); }
export async function getExpression(id:number){return await get<Phrase>(`${adminSelect} WHERE id=?`,[id]);}
export async function getAdminExpressions(filters:AdminFilters){ const clauses:string[]=[];const values:(string|number)[]=[];const q=filters.query?.trim();if(q){clauses.push("(icelandic LIKE ? OR meaning LIKE ? OR literal LIKE ? OR why LIKE ?)");const s=`%${q}%`;values.push(s,s,s,s);}if(filters.translationStatus==="without_audio")clauses.push("(audio_url='' OR audio_url IS NULL)");else if(filters.translationStatus){clauses.push("translation_status=?");values.push(filters.translationStatus);}if(filters.reviewStatus){clauses.push("review_status=?");values.push(filters.reviewStatus);}if(filters.level){clauses.push("level=?");values.push(filters.level);}clauses.push(filters.archived?"archived_at!=''":"archived_at='' ");const facet=`WHERE ${clauses.join(" AND ")}`;const facetValues=[...values];if(filters.source){clauses.push("source=?");values.push(filters.source);}const where=`WHERE ${clauses.join(" AND ")}`;const sorts={icelandic:"icelandic COLLATE NOCASE",level:"level",complexity:"complexity",source:"source",updated:"updated_at"};const sort=sorts[filters.sort??"level"];const dir=filters.direction==="desc"?"DESC":"ASC";const page=Math.max(1,filters.page??1);const size=50;const rows=await all<Phrase>(`${adminSelect} ${where} ORDER BY ${sort} ${dir},id LIMIT ? OFFSET ?`,[...values,size,(page-1)*size]);const total=(await get<{total:number}>(`SELECT COUNT(*) total FROM phrases ${where}`,values))?.total??0;const sources=await all<{source:string;count:number}>(`SELECT source,COUNT(*) count FROM phrases ${facet} GROUP BY source ORDER BY source`,facetValues);const max=(await get<{totalLevels:number}>("SELECT COALESCE(MAX(level),1) totalLevels FROM phrases WHERE archived_at=''"))?.totalLevels??1;return {rows,total,page,pageSize:size,totalPages:Math.max(1,Math.ceil(total/size)),sources,totalLevels:max}; }
export async function getAdminStatistics():Promise<AdminStatistics>{const s=await get<Record<string,number>>("SELECT COUNT(*) total,SUM(translation_status IN ('translated','reviewed')) translated,SUM(review_status='approved') approved,SUM(translation_status IN ('translated','reviewed') AND review_status='approved') ready,SUM(TRIM(meaning)!='') meaning,SUM(TRIM(literal)!='') literal,SUM(TRIM(why)!='') why,SUM(TRIM(meaning)!='' AND TRIM(literal)!='' AND TRIM(why)!='') complete FROM phrases WHERE archived_at='' ");const ts=await all<StatusCount>("SELECT translation_status status,COUNT(*) count FROM phrases WHERE archived_at='' GROUP BY translation_status ORDER BY count DESC");const rs=await all<StatusCount>("SELECT review_status status,COUNT(*) count FROM phrases WHERE archived_at='' GROUP BY review_status ORDER BY count DESC");const sources=await all<AdminStatistics["sources"][number]>("SELECT source,COUNT(*) total,SUM(translation_status IN ('translated','reviewed')) translated,SUM(translation_status='reviewed') reviewed,SUM(review_status='approved') approved,SUM(translation_status='missing') missing FROM phrases WHERE archived_at='' GROUP BY source ORDER BY total DESC,source");const levels=await all<AdminStatistics["levels"][number]>("SELECT level,COUNT(*) total,SUM(translation_status IN ('translated','reviewed')) translated,SUM(review_status='approved') approved FROM phrases WHERE archived_at='' GROUP BY level ORDER BY level");return {total:s?.total??0,translated:s?.translated??0,approved:s?.approved??0,ready:s?.ready??0,translationStatuses:ts,reviewStatuses:rs,completeness:{meaning:s?.meaning??0,literal:s?.literal??0,why:s?.why??0,complete:s?.complete??0},sources,levels};}
function status(requested:TranslationStatus,m:string,l:string,w:string):TranslationStatus{const n=[m,l,w].filter(x=>!x.trim()).length;return n===3?"missing":n?"partly_missing":requested==="missing"||requested==="partly_missing"?"translated":requested;}
export async function updateExpression(id:number,input:ExpressionInput,translatedBy=""){const c=calculateComplexity(input.icelandic);await run("UPDATE phrases SET icelandic=?,english=?,meaning=?,literal=?,why=?,audio_url=?,source=?,category=?,translation_status=?,review_status=?,admin_notes=?,translated_by=CASE WHEN ?!='' THEN ? ELSE translated_by END,complexity=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[input.icelandic,input.meaning,input.meaning,input.literal,input.why,input.audioUrl,input.source,input.category,status(input.translationStatus,input.meaning,input.literal,input.why),input.reviewStatus,input.adminNotes,translatedBy,translatedBy,c,id]);}
export async function updateTranslationDraft(id:number,draft:Partial<Pick<Phrase,"meaning"|"literal"|"why">>,by:string){const p=await get<Phrase>("SELECT meaning,literal,why FROM phrases WHERE id=?",[id]);if(!p)return;const m=draft.meaning??p.meaning,l=draft.literal??p.literal,w=draft.why??p.why;await run("UPDATE phrases SET english=?,meaning=?,literal=?,why=?,translation_status=?,review_status='needs_review',translated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[m,m,l,w,status("draft",m,l,w),by,id]);}
export async function createAdminExpression(input:ExpressionInput){const c=calculateComplexity(input.icelandic);const r=await run("INSERT INTO phrases(icelandic,english,meaning,literal,why,audio_url,source,category,complexity,level,translation_status,review_status,admin_notes) VALUES(?,?,?,?,?,?,?,?,?,0,?,?,?)",[input.icelandic,input.meaning,input.meaning,input.literal,input.why,input.audioUrl,input.source,input.category,c,status(input.translationStatus,input.meaning,input.literal,input.why),input.reviewStatus,input.adminNotes]);return r.lastInsertRowid??0;}
export async function archiveExpression(id:number){await run("UPDATE phrases SET archived_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",[id]);}
export async function unarchiveExpression(id:number){await run("UPDATE phrases SET archived_at='',updated_at=CURRENT_TIMESTAMP WHERE id=?",[id]);}
export async function setExpressionAudio(id:number,url:string){await run("UPDATE phrases SET audio_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[url,id]);}
